# Set the base image
FROM python:3.10.9

# Create a new directory to work in
RUN mkdir /app

# Set the working directory
WORKDIR /app

# Copy the main.py file from the host to the container
COPY . .

# Install dependencies
COPY code/requirements.txt code
RUN pip install -r code/requirements.txt


# Set the entrypoint
ENTRYPOINT ["python", "code/main.py"]